# Generated by Django 4.1.3 on 2022-12-04 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('endereco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=11)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endereco.endereco')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuario.usuario')),
                ('password', models.CharField(max_length=50)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=7)),
                ('data_contrato', models.DateField()),
            ],
            bases=('usuario.usuario',),
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuario.usuario')),
                ('peso', models.DecimalField(decimal_places=1, max_digits=4)),
                ('altura', models.IntegerField()),
                ('tipo_sanguineo', models.CharField(max_length=3)),
            ],
            bases=('usuario.usuario',),
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('funcionario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuario.funcionario')),
                ('especialidade', models.CharField(max_length=100)),
                ('crm', models.CharField(max_length=20)),
            ],
            bases=('usuario.funcionario',),
        ),
    ]
